-- Uncomment the following line (USE statement) if you are executing
-- the query in SQL Server Management Studio so it uses the correct database
--USE [TrailView]

DECLARE @TRAILID UNIQUEIDENTIFIER
DECLARE @GUID297 UNIQUEIDENTIFIER
DECLARE @GUID298 UNIQUEIDENTIFIER
DECLARE @GUID300 UNIQUEIDENTIFIER
DECLARE @GUID301 UNIQUEIDENTIFIER
DECLARE @GUID302 UNIQUEIDENTIFIER
DECLARE @GUID303 UNIQUEIDENTIFIER
DECLARE @GUID311 UNIQUEIDENTIFIER
DECLARE @GUID312 UNIQUEIDENTIFIER
DECLARE @NAME297 VARCHAR(256)
DECLARE @NAME298 VARCHAR(256)
DECLARE @NAME300 VARCHAR(256)
DECLARE @NAME301 VARCHAR(256)
DECLARE @NAME302 VARCHAR(256)
DECLARE @NAME303 VARCHAR(256)
DECLARE @NAME311 VARCHAR(256)
DECLARE @NAME312 VARCHAR(256)

SET @TRAILID = (SELECT TrailId FROM dbo.Trails WHERE Name = 'Cadillac South Ridge Trail')
SET @GUID297 = (SELECT PanoId FROM dbo.Panoramas WHERE PanoNumber = 297)
SET @GUID298 = (SELECT PanoId FROM dbo.Panoramas WHERE PanoNumber = 298)
SET @GUID300 = (SELECT PanoId FROM dbo.Panoramas WHERE PanoNumber = 300)
SET @GUID301 = (SELECT PanoId FROM dbo.Panoramas WHERE PanoNumber = 301)
SET @GUID302 = (SELECT PanoId FROM dbo.Panoramas WHERE PanoNumber = 302)
SET @GUID303 = (SELECT PanoId FROM dbo.Panoramas WHERE PanoNumber = 303)
SET @GUID311 = (SELECT PanoId FROM dbo.Panoramas WHERE PanoNumber = 311)
SET @GUID312 = (SELECT PanoId FROM dbo.Panoramas WHERE PanoNumber = 312)

SET @NAME297 = (SELECT Name FROM dbo.Panoramas WHERE PanoId = @GUID297)
SET @NAME298 = (SELECT Name FROM dbo.Panoramas WHERE PanoId = @GUID298)
SET @NAME300 = (SELECT Name FROM dbo.Panoramas WHERE PanoId = @GUID300)
SET @NAME301 = (SELECT Name FROM dbo.Panoramas WHERE PanoId = @GUID301)
SET @NAME302 = (SELECT Name FROM dbo.Panoramas WHERE PanoId = @GUID302)
SET @NAME303 = (SELECT Name FROM dbo.Panoramas WHERE PanoId = @GUID303)
SET @NAME311 = (SELECT Name FROM dbo.Panoramas WHERE PanoId = @GUID311)
SET @NAME312 = (SELECT Name FROM dbo.Panoramas WHERE PanoId = @GUID312)

DELETE FROM dbo.Links WHERE PanoId = @GUID297 AND Description = 'Forward'
DELETE FROM dbo.Links WHERE PanoId = @GUID300 AND Description = 'Forward'
DELETE FROM dbo.Links WHERE PanoId = @GUID301 AND Description = 'Back'
DELETE FROM dbo.Links WHERE PanoId = @GUID302 AND Description = 'Forward'
DELETE FROM dbo.Links WHERE PanoId = @GUID303 AND Description = 'Back'
DELETE FROM dbo.Links WHERE PanoId = @GUID311 AND Description = 'Forward'
DELETE FROM dbo.Links WHERE PanoId = @GUID312 AND Description = 'Back'

INSERT INTO dbo.Links
VALUES
(NEWID(),
@GUID297,
@TRAILID,
185,
'Forward',
@NAME298,
0),
(NEWID(),
@GUID297,
@TRAILID,
346,
'Forward',
@NAME301,
0),
(NEWID(),
@GUID297,
@TRAILID,
99,
'Forward',
@NAME303,
0),
(NEWID(),
@GUID301,
@TRAILID,
158,
'Back',
@NAME297,
0),
(NEWID(),
@GUID303,
@TRAILID,
233,
'Back',
@NAME297,
0),
(NEWID(),
@GUID311,
@TRAILID,
120,
'Forward',
@NAME312,
0),
(NEWID(),
@GUID312,
@TRAILID,
10,
'Back',
@NAME311,
0)