-- Categories
-- Atmospheric: 0
-- Fauna:       1
-- Flora:       2
-- Landmark:    3

-- Uncomment the following line (USE statement) if you are executing
-- the query in SQL Server Management Studio so it uses the correct database
--USE [TrailView]

DECLARE @TrailId UNIQUEIDENTIFIER
SET @TrailId = (SELECT TrailId FROM dbo.Trails WHERE Name = 'Cadillac South Ridge Trail')

INSERT INTO dbo.PointOfInterests
VALUES
(NEWID(),
206,
312,
@TrailId,
'Common Yellowthroat',
1,
'commonyellowthroat.png',
'cy.mp3',
'During the last third of the trail, be on the lookout for the distinctive "witchety witchety witchety" call of the Common Yellowthroat. This small warbler is more often heard than seen, but can be found foraging in the low brush.'),
(NEWID(),
159,
312,
@TrailId,
'White-Throated Sparrow',
1,
'whitethroatedsparrow.png',
'wts2.mp3',
'From about the halfway point up until the summit, you are likely the hear the slow, clear, syncopated song of the White-Throated Sparrow. These little birds are often found singing their hearts out on high tree branches.'),
(NEWID(),
45,
45,
@TrailId,
'Woodpecker Activity',
1,
'woodpecker3110.png',
null,
'Large, rectangular holes are the hallmark of the Pileated Woodpecker. Tree damage like this reveals that woodpeckers have paid a visit, drilling for ants and termites that live within. Keep an ear out for a loud, rattling "ah-ah-ah" and you may spot the often-elusive crow-sized bird that emits it.'),
(NEWID(),
75,
75,
@TrailId,
'Woodpecker Activity',
1,
'woodpecker3260.png',
null,
'Large, rectangular holes are the hallmark of the Pileated Woodpecker. Tree damage like this reveals that woodpeckers have paid a visit, drilling for ants and termites that live within. Keep an ear out for a loud, rattling "ah-ah-ah" and you may spot the often-elusive crow-sized bird that emits it.'),
(NEWID(),
204,
204,
@TrailId,
'Frogs',
1,
null,
'lake1.mp3',
'Although rarely seen, the frogs that reside in Featherbed Pond will give you quite a vocal performance as you walk by!'),
(NEWID(),
17,
17,
@TrailId,
'Glacial Erratic',
3,
'glacialerratic2968.png',
null,
'A large boulder that seems out of place and may not be composed of the same materials as surrounding rock may have been dropped by a glacier in the distant past. These rocks are known as glacial erratics and are found in many locations around Mount Desert Island.'),
(NEWID(),
83,
84,
@TrailId,
'Signpost',
3,
'signpost3302.png',
null,
null),
(NEWID(),
204,
204,
@TrailId,
'Featherbed Pond',
3,
'lake3556.png',
'lake1.mp3',
'About two-thirds of the way through the hike, you will reach Featherbed pond, a small, secluded body of water just to the side of the trail. Here there is a small wooden bench where hikers can take a rest and enjoy the chorus of croaking frogs and buzzing dragonflies.'),
(NEWID(),
110,
312,
@TrailId,
'Blueberry Bushes',
2,
'blueberries3556.png',
null,
'Be on the lookout for juicy blueberries growing along the last two thirds of the trail starting in early July!'),
(NEWID(),
28,
28,
@TrailId,
'Caribou Lichen',
2,
'lichen3023.png',
null,
null),
(NEWID(),
19,
19,
@TrailId,
'Yellow Mushrooms',
2,
'mushrooms2978.png',
null,
null),
(NEWID(),
22,
22,
@TrailId,
'Widowmaker',
2,
'widowmaker2993.png',
null,
'Dead trees that have fallen and are being held up by other trees are known as widowmakers due to the risk that they may become suddenly dislodged. This widowmaker is well off to the side of the trail and does not pose any risk to hikers of South Ridge.'),
(NEWID(),
72,
72,
@TrailId,
'Steps',
3,
'steps3245.png',
null,
null),
(NEWID(),
40,
40,
@TrailId,
'Sandbags',
3,
'sandbags3084.png',
null,
null),
(NEWID(),
41,
41,
@TrailId,
'Drainage',
3,
'drainage3089.png',
null,
null),
(NEWID(),
46,
46,
@TrailId,
'Woodpecker Activity',
1,
'woodpeckertree3115.png',
null,
'Large, rectangular holes are the hallmark of the Pileated Woodpecker. Tree damage like this reveals that woodpeckers have paid a visit, drilling for ants and termites that live within. Keep an ear out for a loud, rattling "ah-ah-ah" and you may spot the often-elusive crow-sized bird that emits it.'),
(NEWID(),
0,
102,
@TrailId,
'Black Throated Green Warbler',
1,
'blackthroatedgreenwarbler.png',
'btgw.mp3',
'Throughout the woodsy first third of the hike, listen for the omnipresent five-note call of the Black-Throated Green Warbler. This bird is likely to stay out of sight high in the canopy of coniferous forests, but keep an eye out for a flash of yellow, as he might occasionally come down for a closer look.'),
(NEWID(),
0,
102,
@TrailId,
'Hermit Thrush',
1,
null,
'hermitthrush.mp3',
'During the woodsy first mile of your hike, keep an ear out for the haunting, echoing song of the Hermit Thrush. These small brown and white spotted birds blend in with their surroundings, making them difficult to spot, but their song is pervasive and considered one of the most beautiful of the North American birds.'),
(NEWID(),
50,
50,
@TrailId,
'Marsh',
3,
'marsh3135.png',
null,
null),
(NEWID(),
86,
86,
@TrailId,
'Rock Wall',
3,
'rockwall3319.png',
null,
null),
(NEWID(),
98,
98,
@TrailId,
'Cairn',
3,
'cairn3379.png',
null,
'Cairns are manmade rock structures built to guide hikers. They will indicate the path of the trail for the last two thirds of your hike. Do not deconstruct or build more cairns.'),
(NEWID(),
93,
93,
@TrailId,
'Spider Web',
1,
'spiderweb3354.png',
null,
null),
(NEWID(),
38,
38,
@TrailId,
'Dead Man''s Fingers Lichen',
2,
'coolplants3094.png',
null,
null),
(NEWID(),
37,
37,
@TrailId,
'Shell Fungus',
2,
'bigmushroom3069.png',
null,
null),
(NEWID(),
32,
32,
@TrailId,
'Sap',
2,
'sap3034.png',
null,
null),
(NEWID(),
44,
44,
@TrailId,
'Drainage',
3,
'drainage3105.png',
null,
null),
(NEWID(),
6,
6,
@TrailId,
'Planks',
3,
'plank2913.png',
null,
null),
(NEWID(),
121,
121,
@TrailId,
'Sheep Laurel',
2,
'pinkflower3612.png',
null,
null),
(NEWID(),
167,
167,
@TrailId,
'Wind Gusts of 8.9 mph',
0,
null,
null,
null),
(NEWID(),
182,
182,
@TrailId,
'Wind Gusts of 9.7 mph',
0,
null,
null,
null),
(NEWID(),
312,
312,
@TrailId,
'Wind Gusts of 17.5 mph',
0,
null,
null,
null),
(NEWID(),
204,
204,
@TrailId,
'Chalk-Fronted Corporal Dragonfly',
1,
'dragonfly4040.png',
null,
'These black-and-white dragonflies are abundant around Featherbed Pond, buzzing over the water and around its shore.'),
(NEWID(),
205,
205,
@TrailId,
'Signpost',
3,
'signpost4045.png',
null,
null),
(NEWID(),
217,
217,
@TrailId,
'Meadowsweet',
2,
'whiteflowers4105.png',
null,
null),
(NEWID(),
217,
312,
@TrailId,
'Turkey Vultures',
1,
null,
null,
'Turkey vultures can often be found soaring overhead scavanging for food. You can recognize these large raptors in flight by their black and white underwing, small head, and the way they hold their wings in a V-shape while flying.'),
(NEWID(),
214,
214,
@TrailId,
'Dog Rose',
2,
'pinkflowers4090.png',
null,
null),
(NEWID(),
226,
226,
@TrailId,
'Glacial Erratic',
3,
'glacialerratic4150.png',
null,
'A large boulder that seems out of place and may not be composed of the same materials as surrounding rock may have been dropped by a glacier in the distant past. These rocks are known as glacial erratics and are found in many locations around Mount Desert Island.'),
(NEWID(),
248,
248,
@TrailId,
'Signpost',
3,
'signpost4264.png',
null,
null),
(NEWID(),
264,
264,
@TrailId,
'Blue Hill Overlook',
3,
'bluehilloverlook4344.png',
null,
'For people who choose to drive up Cadillac Mountain, Blue Hill Overlook is a pull-off that allows for stopping to enjoy the beautiful views.'),
(NEWID(),
266,
266,
@TrailId,
'Iron Rung',
3,
'rung4359.png',
null,
'Iron rungs are common on some of Acadia''s trails to provide hand and footholds to hikers during difficult climbs. South Ridge Trail contains only one iron rung to assist hikers on one of the harder step-ups near the end of the trail.'),
(NEWID(),
288,
288,
@TrailId,
'Signpost',
3,
'signpost4469.png',
null,
null),
(NEWID(),
308,
308,
@TrailId,
'Signpost',
3,
'signpost4571.png',
null,
null),
(NEWID(),
303,
303,
@TrailId,
'Highest Point',
3,
'highestpoint4544.png',
null,
'This inset marks the highest point on Cadillac Mountain, an unassuming rock very close to the exit of the South Ridge. At this point, the elevation is 1530 feet above sea level.'),
(NEWID(),
153,
153,
@TrailId,
'Cicadas',
1,
null,
'cicadas.mp3',
null)